export const ORDER_ACTION = {
  PROCEED: 'PROCEED',
  CANCEL_BEFORE_PAYMENT: 'CANCEL_BEFORE_PAYMENT',
  CANCEL_AFTER_PAYMENT: 'CANCEL_AFTER_PAYMENT',
  CANCEL_REQUEST: 'CANCEL_REQUEST',
} as const;

export type OrderAction = (typeof ORDER_ACTION)[keyof typeof ORDER_ACTION];
