export const UPDATE_SCENARIO = {
  PENDING_TO_PREPARING: 'PENDING_TO_PREPARING',
  PREPARING_TO_SHIPPING: 'PREPARING_TO_SHIPPING',
  SHIPPING_TO_DELIVERED: 'SHIPPING_TO_DELIVERED',
} as const;

export type UpdateScenario = (typeof UPDATE_SCENARIO)[keyof typeof UPDATE_SCENARIO];

export const CANCEL_SCENARIO = {
  PAID_ORDER_TO_CANCELLED: 'PAYED_ORDER_TO_CANCELLED',
  BEFORE_PAYMENT_TO_CANCELLED: 'BEFORE_PAYMENT_TO_CANCELLED',
  CANCEL_REQUEST_TO_CANCELLED: 'CANCEL_REQUEST_TO_CANCELLED',
} as const;

export type CancelScenario = (typeof CANCEL_SCENARIO)[keyof typeof CANCEL_SCENARIO];
