export const STATUS_UPDATE_ACTION = {
  PENDING_TO_PREPARING: 'PENDING_TO_PREPARING',
  PREPARING_TO_SHIPPING: 'PREPARING_TO_SHIPPING',
  SHIPPING_TO_DELIVERED: 'SHIPPING_TO_DELIVERED',
  ORDER_TO_CANCELLED: 'ORDER_TO_CANCELLED',
} as const;

export type StatusUpdateAction = (typeof STATUS_UPDATE_ACTION)[keyof typeof STATUS_UPDATE_ACTION];

export const STATUS_UPDATE_ACTION_NAME = {
  [STATUS_UPDATE_ACTION.PENDING_TO_PREPARING]: '입금확인중에서 상품준비로 변경',
  [STATUS_UPDATE_ACTION.PREPARING_TO_SHIPPING]: '상품준비에서 배송시작으로 변경',
  [STATUS_UPDATE_ACTION.SHIPPING_TO_DELIVERED]: '배송시작에서 배송완료로 변경',
  [STATUS_UPDATE_ACTION.ORDER_TO_CANCELLED]: '주문 취소처리',
} as const;
