/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    image: Image;
    files: File;
    product: Product;
    'product-category': ProductCategory;
    'point-history': PointHistory;
    'order-status': OrderStatus;
    order: Order;
    'point-for-transation': PointForTransation;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    image: ImageSelect<false> | ImageSelect<true>;
    files: FilesSelect<false> | FilesSelect<true>;
    product: ProductSelect<false> | ProductSelect<true>;
    'product-category': ProductCategorySelect<false> | ProductCategorySelect<true>;
    'point-history': PointHistorySelect<false> | PointHistorySelect<true>;
    'order-status': OrderStatusSelect<false> | OrderStatusSelect<true>;
    order: OrderSelect<false> | OrderSelect<true>;
    'point-for-transation': PointForTransationSelect<false> | PointForTransationSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    popup: Popup;
    terms: Term;
    'privacy-policy': PrivacyPolicy;
  };
  globalsSelect: {
    popup: PopupSelect<false> | PopupSelect<true>;
    terms: TermsSelect<false> | TermsSelect<true>;
    'privacy-policy': PrivacyPolicySelect<false> | PrivacyPolicySelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    username: string;
  };
  login: {
    password: string;
    username: string;
  };
  registerFirstUser: {
    password: string;
    username: string;
  };
  unlock: {
    username: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * 유저 타입을 선택해주세요
   */
  role?: ('admin' | 'client') | null;
  /**
   * 승인 여부를 선택해주세요 (체크 시 회원가입이 승인됩니다)
   */
  isApproved?: boolean | null;
  /**
   * 대표자명을 입력해주세요
   */
  ceo?: string | null;
  /**
   * 병원명을 입력해주세요
   */
  hospitalName?: string | null;
  /**
   * 주소를 입력해주세요
   */
  address?: string | null;
  /**
   * 사업자등록번호를 입력해주세요
   */
  businessNumber?: string | null;
  /**
   * 요양기관번호를 입력해주세요
   */
  nursingNumber?: string | null;
  /**
   * 전화번호를 입력해주세요
   */
  phoneNumber?: string | null;
  /**
   * FAX번호를 입력해주세요
   */
  faxNumber?: string | null;
  /**
   * 증빙서류를 업로드해주세요
   */
  fileList?: (number | File)[] | null;
  /**
   * 적립금을 입력해주세요
   */
  point?: number | null;
  updatedAt: string;
  createdAt: string;
  /**
   * 이메일을 입력해주세요
   */
  email?: string | null;
  /**
   * 아이디를 입력해주세요
   */
  username: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "files".
 */
export interface File {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "image".
 */
export interface Image {
  id: number;
  /**
   * 이미지 설명에 해당되는 부분으로 필수는 아니지만 SEO가 중요하다면 설정해주세요
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product".
 */
export interface Product {
  id: number;
  image?: (number | null) | Image;
  name: string;
  category?: (number | null) | ProductCategory;
  insurance_code?: string | null;
  manufacturer: string;
  price: number;
  /**
   * 카드 결제 적립금 비율을 퍼센트로 입력해주세요 (ex: 1.5)
   * 최대 1.8까지 입력 가능합니다.
   */
  cashback_rate: number;
  /**
   * 무통장 입금 적립금 비율을 퍼센트로 입력해주세요 (ex: 1.5)
   * 최대 1.8까지 입력 가능합니다.
   */
  cashback_rate_for_bank: number;
  specification?: string | null;
  stock: number;
  delivery_fee: number;
  /**
   * 반품가능여부를 선택해주세요 (체크 시 반품가능)
   */
  returnable: boolean;
  /**
   * 인기 제품 여부를 선택해주세요 (체크 시 인기 제품)
   */
  is_best_product: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-category".
 */
export interface ProductCategory {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "point-history".
 */
export interface PointHistory {
  id: number;
  user: number | User;
  type: 'earn' | 'use' | 'cancel';
  balanceAfter?: number | null;
  reason: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-status".
 */
export interface OrderStatus {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order".
 */
export interface Order {
  id: number;
  user: number | User;
  product: number | Product;
  orderCreatedAt: string;
  paymentsMethod: 'creditCard' | 'bankTransfer';
  pgCno?: string | null;
  quantity: number;
  orderStatus: number | OrderStatus;
  orderRequest?: string | null;
  pointForTransation?: (number | null) | PointForTransation;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "point-for-transation".
 */
export interface PointForTransation {
  id: number;
  user: number | User;
  usedPointAmount: number;
  transactionPgCno?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'image';
        value: number | Image;
      } | null)
    | ({
        relationTo: 'files';
        value: number | File;
      } | null)
    | ({
        relationTo: 'product';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'product-category';
        value: number | ProductCategory;
      } | null)
    | ({
        relationTo: 'point-history';
        value: number | PointHistory;
      } | null)
    | ({
        relationTo: 'order-status';
        value: number | OrderStatus;
      } | null)
    | ({
        relationTo: 'order';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'point-for-transation';
        value: number | PointForTransation;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  isApproved?: T;
  ceo?: T;
  hospitalName?: T;
  address?: T;
  businessNumber?: T;
  nursingNumber?: T;
  phoneNumber?: T;
  faxNumber?: T;
  fileList?: T;
  point?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  username?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "image_select".
 */
export interface ImageSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "files_select".
 */
export interface FilesSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product_select".
 */
export interface ProductSelect<T extends boolean = true> {
  image?: T;
  name?: T;
  category?: T;
  insurance_code?: T;
  manufacturer?: T;
  price?: T;
  cashback_rate?: T;
  cashback_rate_for_bank?: T;
  specification?: T;
  stock?: T;
  delivery_fee?: T;
  returnable?: T;
  is_best_product?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-category_select".
 */
export interface ProductCategorySelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "point-history_select".
 */
export interface PointHistorySelect<T extends boolean = true> {
  user?: T;
  type?: T;
  balanceAfter?: T;
  reason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-status_select".
 */
export interface OrderStatusSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order_select".
 */
export interface OrderSelect<T extends boolean = true> {
  user?: T;
  product?: T;
  orderCreatedAt?: T;
  paymentsMethod?: T;
  pgCno?: T;
  quantity?: T;
  orderStatus?: T;
  orderRequest?: T;
  pointForTransation?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "point-for-transation_select".
 */
export interface PointForTransationSelect<T extends boolean = true> {
  user?: T;
  usedPointAmount?: T;
  transactionPgCno?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "popup".
 */
export interface Popup {
  id: number;
  popupItems?:
    | {
        /**
         * 이미지만 표시하려면 체크해주세요
         */
        isOnlyImage?: boolean | null;
        /**
         * 이미지를 선택해주세요
         */
        image?: (number | null) | Image;
        /**
         * 내용을 입력해주세요
         */
        content?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms".
 */
export interface Term {
  id: number;
  /**
   * 이용약관 내용을 입력해주세요
   */
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy".
 */
export interface PrivacyPolicy {
  id: number;
  /**
   * 개인정보처리방침 내용을 입력해주세요
   */
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "popup_select".
 */
export interface PopupSelect<T extends boolean = true> {
  popupItems?:
    | T
    | {
        isOnlyImage?: T;
        image?: T;
        content?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms_select".
 */
export interface TermsSelect<T extends boolean = true> {
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy_select".
 */
export interface PrivacyPolicySelect<T extends boolean = true> {
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}