/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    image: Image;
    files: File;
    product: Product;
    'product-category': ProductCategory;
    'product-price': ProductPrice;
    order: Order;
    'order-product': OrderProduct;
    'recent-purchased-history': RecentPurchasedHistory;
    payment: Payment;
    'point-transaction': PointTransaction;
    favorites: Favorite;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    order: {
      orderProducts: 'order-product';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    image: ImageSelect<false> | ImageSelect<true>;
    files: FilesSelect<false> | FilesSelect<true>;
    product: ProductSelect<false> | ProductSelect<true>;
    'product-category': ProductCategorySelect<false> | ProductCategorySelect<true>;
    'product-price': ProductPriceSelect<false> | ProductPriceSelect<true>;
    order: OrderSelect<false> | OrderSelect<true>;
    'order-product': OrderProductSelect<false> | OrderProductSelect<true>;
    'recent-purchased-history': RecentPurchasedHistorySelect<false> | RecentPurchasedHistorySelect<true>;
    payment: PaymentSelect<false> | PaymentSelect<true>;
    'point-transaction': PointTransactionSelect<false> | PointTransactionSelect<true>;
    favorites: FavoritesSelect<false> | FavoritesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    popup: Popup;
    terms: Term;
    'privacy-policy': PrivacyPolicy;
    'meta-setting': MetaSetting;
  };
  globalsSelect: {
    popup: PopupSelect<false> | PopupSelect<true>;
    terms: TermsSelect<false> | TermsSelect<true>;
    'privacy-policy': PrivacyPolicySelect<false> | PrivacyPolicySelect<true>;
    'meta-setting': MetaSettingSelect<false> | MetaSettingSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    username: string;
  };
  login: {
    password: string;
    username: string;
  };
  registerFirstUser: {
    password: string;
    username: string;
  };
  unlock: {
    username: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * 유저 타입을 선택해주세요
   */
  role?: ('admin' | 'client') | null;
  /**
   * 회원가입 승인 여부를 선택해주세요 활성화 시 회원가입이 승인됩니다
   */
  isApproved?: boolean | null;
  point?: number | null;
  ceo?: string | null;
  hospitalName?: string | null;
  doctorLicenseNumber?: string | null;
  businessNumber?: string | null;
  nursingNumber?: string | null;
  address?: string | null;
  contactEmail?: string | null;
  phoneNumber?: string | null;
  faxNumber?: string | null;
  fileList?: (number | File)[] | null;
  updatedAt: string;
  createdAt: string;
  email?: string | null;
  username: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "files".
 */
export interface File {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "image".
 */
export interface Image {
  id: number;
  /**
   * 필수x, 이미지 설명을 입력해주세요. ex) 제품명
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product".
 */
export interface Product {
  id: number;
  image?: (number | null) | Image;
  name: string;
  category?: (number | null) | ProductCategory;
  insurance_code?: string | null;
  specification?: string | null;
  manufacturer: string;
  ingredient?: string | null;
  stock: number;
  /**
   * 인기 제품 여부를 선택해주세요 (체크 시 주문 페이지 상단에 표시됩니다.)
   */
  is_best_product?: boolean | null;
  /**
   * 반품가능여부를 선택해주세요 (체크 시 반품가능)
   */
  returnable: boolean;
  price: number;
  /**
   * 카드 결제 적립금 비율을 퍼센트로 입력해주세요 (ex: 1.5)
   * 최대 1.8까지 입력 가능합니다.
   */
  cashback_rate: number;
  /**
   * 무통장 입금 적립금 비율을 퍼센트로 입력해주세요 (ex: 1.5)
   * 최대 1.8까지 입력 가능합니다.
   */
  cashback_rate_for_bank: number;
  delivery_fee: number;
  /**
   * 수량 당 배송비를 계산할지에 대한 여부를 설정할 수 있습니다. 활성화 시 배송비는 수량 * 배송비로 계산됩니다.
   */
  is_cost_per_unit: boolean;
  /**
   * 최소 주문 금액 이상 시 배송비 무료 여부를 선택해주세요
   *  활성화 시 최소주문 금액 이상 주문건에 대한 배송비는 0원으로 처리됩니다
   */
  is_free_delivery: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-category".
 */
export interface ProductCategory {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-price".
 */
export interface ProductPrice {
  id: number;
  product: number | Product;
  user: number | User;
  price: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order".
 */
export interface Order {
  id: number;
  user: number | User;
  orderProducts?: {
    docs?: (number | OrderProduct)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  paymentsMethod: 'creditCard' | 'bankTransfer';
  orderStatus: 'preparing' | 'shipping' | 'delivered' | 'cancelled' | 'pending';
  orderDeliveryFee?: number | null;
  orderRequest?: string | null;
  orderNo: string;
  finalPrice: number;
  usedPoint: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-product".
 */
export interface OrderProduct {
  id: number;
  product: number | Product;
  order: number | Order;
  orderProductStatus: 'pending' | 'preparing' | 'shipping' | 'delivered' | 'cancel_request' | 'cancelled';
  productNameSnapshot?: string | null;
  priceSnapshot: number;
  totalAmount: number;
  productDeliveryFee: number;
  quantity: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recent-purchased-history".
 */
export interface RecentPurchasedHistory {
  id: number;
  user: number | User;
  product: number | Product;
  quantity: number;
  amount: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment".
 */
export interface Payment {
  id: number;
  order: number | Order;
  pgCno: string;
  amount: number;
  paymentsMethod: 'creditCard';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "point-transaction".
 */
export interface PointTransaction {
  id: number;
  user?: (number | null) | User;
  orderProduct?: (number | null) | OrderProduct;
  type: 'USE' | 'EARN' | 'CANCEL_USE' | 'CANCEL_EARN';
  reason?: string | null;
  amount: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favorites".
 */
export interface Favorite {
  id: number;
  user: number | User;
  product: number | Product;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'image';
        value: number | Image;
      } | null)
    | ({
        relationTo: 'files';
        value: number | File;
      } | null)
    | ({
        relationTo: 'product';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'product-category';
        value: number | ProductCategory;
      } | null)
    | ({
        relationTo: 'product-price';
        value: number | ProductPrice;
      } | null)
    | ({
        relationTo: 'order';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'order-product';
        value: number | OrderProduct;
      } | null)
    | ({
        relationTo: 'recent-purchased-history';
        value: number | RecentPurchasedHistory;
      } | null)
    | ({
        relationTo: 'payment';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'point-transaction';
        value: number | PointTransaction;
      } | null)
    | ({
        relationTo: 'favorites';
        value: number | Favorite;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  isApproved?: T;
  point?: T;
  ceo?: T;
  hospitalName?: T;
  doctorLicenseNumber?: T;
  businessNumber?: T;
  nursingNumber?: T;
  address?: T;
  contactEmail?: T;
  phoneNumber?: T;
  faxNumber?: T;
  fileList?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  username?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "image_select".
 */
export interface ImageSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "files_select".
 */
export interface FilesSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product_select".
 */
export interface ProductSelect<T extends boolean = true> {
  image?: T;
  name?: T;
  category?: T;
  insurance_code?: T;
  specification?: T;
  manufacturer?: T;
  ingredient?: T;
  stock?: T;
  is_best_product?: T;
  returnable?: T;
  price?: T;
  cashback_rate?: T;
  cashback_rate_for_bank?: T;
  delivery_fee?: T;
  is_cost_per_unit?: T;
  is_free_delivery?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-category_select".
 */
export interface ProductCategorySelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-price_select".
 */
export interface ProductPriceSelect<T extends boolean = true> {
  product?: T;
  user?: T;
  price?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order_select".
 */
export interface OrderSelect<T extends boolean = true> {
  user?: T;
  orderProducts?: T;
  paymentsMethod?: T;
  orderStatus?: T;
  orderDeliveryFee?: T;
  orderRequest?: T;
  orderNo?: T;
  finalPrice?: T;
  usedPoint?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-product_select".
 */
export interface OrderProductSelect<T extends boolean = true> {
  product?: T;
  order?: T;
  orderProductStatus?: T;
  productNameSnapshot?: T;
  priceSnapshot?: T;
  totalAmount?: T;
  productDeliveryFee?: T;
  quantity?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recent-purchased-history_select".
 */
export interface RecentPurchasedHistorySelect<T extends boolean = true> {
  user?: T;
  product?: T;
  quantity?: T;
  amount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment_select".
 */
export interface PaymentSelect<T extends boolean = true> {
  order?: T;
  pgCno?: T;
  amount?: T;
  paymentsMethod?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "point-transaction_select".
 */
export interface PointTransactionSelect<T extends boolean = true> {
  user?: T;
  orderProduct?: T;
  type?: T;
  reason?: T;
  amount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favorites_select".
 */
export interface FavoritesSelect<T extends boolean = true> {
  user?: T;
  product?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "popup".
 */
export interface Popup {
  id: number;
  popupItems?:
    | {
        /**
         * 이미지만 표시하려면 체크해주세요
         */
        isOnlyImage?: boolean | null;
        /**
         * 이미지를 선택해주세요
         */
        image?: (number | null) | Image;
        /**
         * 내용을 입력해주세요
         */
        content?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms".
 */
export interface Term {
  id: number;
  /**
   * 이용약관 내용을 입력해주세요
   */
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy".
 */
export interface PrivacyPolicy {
  id: number;
  /**
   * 개인정보처리방침 내용을 입력해주세요
   */
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "meta-setting".
 */
export interface MetaSetting {
  id: number;
  /**
   * 배송비 무료를 적용할 최소 주문 금액을 설정해주세요
   */
  min_order_price?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "popup_select".
 */
export interface PopupSelect<T extends boolean = true> {
  popupItems?:
    | T
    | {
        isOnlyImage?: T;
        image?: T;
        content?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms_select".
 */
export interface TermsSelect<T extends boolean = true> {
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy_select".
 */
export interface PrivacyPolicySelect<T extends boolean = true> {
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "meta-setting_select".
 */
export interface MetaSettingSelect<T extends boolean = true> {
  min_order_price?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}